format = """
$username@$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$rust\
$lua\
$python\
$line_break\
$character"""

# blank line between prompts
add_newline = true

# disable package module
[package]
disabled = false
symbol = "pack "

# single line prompt
[line_break]
disabled = false 

# Replace the "❯" symbol in the prompt with "➜"
[character]                            
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

### git ###

# branches
[git_branch]
symbol = " "
style = "bold purple"

# commits
[git_commit]
style = "bold green"
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"

# status
[git_status]
conflicted = "="
ahead = "⇡"
behind = "⇣"
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
style = "bold red"
disabled = false

### git end ###

# user
[username]
style_user = "bold white"
style_root = "bold red"
format = "[$user]($style)"
disabled = false
show_always = true

# host
[hostname]
ssh_only = false
format = "[$hostname ]($style)"
style = "bold white"
disabled = false

[directory]
read_only = " "

[python]
symbol = "py "

[rust]
symbol = "rs "

[lua]
symbol = "lua "
