[line_break]
disabled = false

# blank line between prompts
add_newline = true

# disable package module
[package]
disabled = false
symbol = " "

# single line prompt
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            
success_symbol = "[➜](bold green)"

### git ###

# branches
[git_branch]
symbol = " "
style = "bold purple"

# commits
[git_commit]
style = "bold green"
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"

# status
[git_status]
conflicted = "="
ahead = "⇡"
behind = "⇣"
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
style = "bold red"
disabled = false

### git end ###

# user
[username]
style_user = "bold white"
style_root = "bold red"
format = "[$user ]($style)"
disabled = false
show_always = true

[directory]
read_only = " "

[python]
symbol = " "

[rust]
symbol = " "

[lua]
symbol = "☽ "
